### PR TITLE
Remove ActiveRecord ahead of deploying to preview

### PR DESCRIPTION
**Pull request by tekin**
The authenticating-proxy will need a database to store gds-sso session information at some point, but the machines where the app is being installed only have mongo available.

### CODE REVIEW

**Comment by mattbostock** [comment]
Does that mean that this application will use Mongo? I understood we're aiming at using PostgreSQL for new applications.

**Comment by tekin** [comment]
This app is proxying between varnish and  the router, both of which live on the cache boxes. The cache boxes have mongo on them, so we're going to use that. It's only needed for storing gds-sso user sessions, so we can live with simply using mongo.

**Comment by mattbostock** [comment]
Mongo is installed on the `router-backend` boxes rather than the `cache` boxes.

There's no PostgreSQL instance in the Draft stack currently, but I'd argue it's worth adding if that's what we're moving to. Do you have any preference, @bradleywright?

**Comment by jamiecobbett** [comment]
The changes in of themselves look good :+1:

**Comment by bradleywright** [comment]
The cache boxes can see the Mongo in router-backend (the Router accesses Mongo directly).

I'd rather not add an entire database just for this app.

**Comment by bradleywright** [comment]
Also if we add a Postgres instance to the API tier, we'll have to punch a hole for apps in cache to access API, which would be really bad.

**Comment by mattbostock** [comment]
What if we added PostgreSQL to the router-backend machines?

**Comment by bradleywright** [comment]
@mattbostock how would we add that? We'd need separate machines wouldn't we? (eg `postgres-{primary,secondary}-1.cache`, rather than adding them to the backend boxes.

**Comment by mattbostock** [comment]
Discussion in meatspace: Since this application is currently being prototyped and switching databases later should be relatively easy, it'll use Mongo for now.

**Pull request merged**
