### PR TITLE
Add airbrake for errbit error reporting

### PR DESCRIPTION
**Pull request by tekin**
This installs the dependencies and sets up an ENV-based configuration.
Additional changes will need to be made to puppet to set these env-vars and also to the hiera data for preview, staging and production.

### CODE REVIEW

**Comment by jamiecobbett** [comment]
This covers the development environment - is there a PR required in https://github.gds/gds/deployment ?

**Comment by tekin** [comment]
Yep, environment variables will need to be configured appropriately for the relevant deployment environments. I don't have access to the `deployment` repo though, so that will have to come later and with someone else's help. The config is written such that if the variables are absent, airbrake will not run, so it's a safe noop.

**Comment by jamiecobbett** [comment]
@tekin whoops - I meant to write that comment on the puppet PR.

If you're testing the changes, I think the following will need to happen:
* gds/deployment changes get merged
* puppet deployed (I don't think gds/deployment changes trigger preview deploys)
* puppet runs on the relevant machines (up to 30 minutes after puppet deploy)
* restart/redeploy this app

**Comment by tekin** [comment]
Thanks @jamiecobbett. We'll deploying it to preview soon so we can run through these steps then.

**Pull request merged**
